package as3.controls 
{
	/**
	 * ...
	 * @author hbb
	 */
	public class ProvinceCityData
	{
		
	public static const xml:XML =
<data>
	<prov label="安徽">
		<city label="合肥" />
		<city label="安庆" />
		<city label="蚌埠" />
		<city label="亳州" />
		<city label="巢湖" />
		<city label="滁州" />
		<city label="阜阳" />
		<city label="贵池" />
		<city label="淮北" />
		<city label="淮化" />
		<city label="淮南" />
		<city label="黄山" />
		<city label="九华山" />
		<city label="六安" />
		<city label="马鞍山" />
		<city label="宿州" />
		<city label="铜陵" />
		<city label="屯溪" />
		<city label="芜湖" />
		<city label="宣城" />
	</prov>
	<prov label="北京">
		<city label="东城" />
		<city label="西城" />
		<city label="崇文" />
		<city label="宣武" />
		<city label="朝阳" />
		<city label="丰台" />
		<city label="石景山" />
		<city label="海淀" />
		<city label="门头沟" />
		<city label="房山" />
		<city label="通州" />
		<city label="顺义" />
		<city label="昌平" />
		<city label="大兴" />
		<city label="平谷" />
		<city label="怀柔" />
		<city label="密云" />
		<city label="延庆" />
	</prov>
	<prov label="重庆">
		<city label="万州" />
		<city label="涪陵" />
		<city label="渝中" />
		<city label="大渡口" />
		<city label="江北" />
		<city label="沙坪坝" />
		<city label="九龙坡" />
		<city label="南岸" />
		<city label="北碚" />
		<city label="万盛" />
		<city label="双挢" />
		<city label="渝北" />
		<city label="巴南" />
		<city label="黔江" />
		<city label="长寿" />
		<city label="綦江" />
		<city label="潼南" />
		<city label="铜梁" />
		<city label="大足" />
		<city label="荣昌" />
		<city label="壁山" />
		<city label="梁平" />
		<city label="城口" />
		<city label="丰都" />
		<city label="垫江" />
		<city label="武隆" />
		<city label="忠县" />
		<city label="开县" />
		<city label="云阳" />
		<city label="奉节" />
		<city label="巫山" />
		<city label="巫溪" />
		<city label="石柱" />
		<city label="秀山" />
		<city label="酉阳" />
		<city label="彭水" />
		<city label="江津" />
		<city label="合川" />
		<city label="永川" />
		<city label="南川" />
	</prov>
	<prov label="福建">
		<city label="福州" />
		<city label="福安" />
		<city label="龙岩" />
		<city label="南平" />
		<city label="宁德" />
		<city label="莆田" />
		<city label="泉州" />
		<city label="三明" />
		<city label="邵武" />
		<city label="石狮" />
		<city label="永安" />
		<city label="武夷山" />
		<city label="厦门" />
		<city label="漳州" />
	</prov>
	<prov label="甘肃">
		<city label="兰州" />
		<city label="白银" />
		<city label="定西" />
		<city label="敦煌" />
		<city label="甘南" />
		<city label="金昌" />
		<city label="酒泉" />
		<city label="临夏" />
		<city label="平凉" />
		<city label="天水" />
		<city label="武都" />
		<city label="武威" />
		<city label="西峰" />
		<city label="张掖" />
	</prov>
	<prov label="广东">
		<city label="广州" />
		<city label="潮阳" />
		<city label="潮州" />
		<city label="澄海" />
		<city label="东莞" />
		<city label="佛山" />
		<city label="河源" />
		<city label="惠州" />
		<city label="江门" />
		<city label="揭阳" />
		<city label="开平" />
		<city label="茂名" />
		<city label="梅州" />
		<city label="清远" />
		<city label="汕头" />
		<city label="汕尾" />
		<city label="韶关" />
		<city label="深圳" />
		<city label="顺德" />
		<city label="阳江" />
		<city label="英德" />
		<city label="云浮" />
		<city label="增城" />
		<city label="湛江" />
		<city label="肇庆" />
		<city label="中山" />
		<city label="珠海" />
	</prov>
	<prov label="广西">
		<city label="南宁" />
		<city label="百色" />
		<city label="北海" />
		<city label="桂林" />
		<city label="防城港" />
		<city label="河池" />
		<city label="贺州" />
		<city label="柳州" />
		<city label="钦州" />
		<city label="梧州" />
		<city label="玉林" />
	</prov>
	<prov label="贵州">
		<city label="贵阳" />
		<city label="安顺" />
		<city label="毕节" />
		<city label="都匀" />
		<city label="凯里" />
		<city label="六盘水" />
		<city label="铜仁" />
		<city label="兴义" />
		<city label="玉屏" />
		<city label="遵义" />
	</prov>
	<prov label="海南">
		<city label="海口" />
		<city label="儋县" />
		<city label="陵水" />
		<city label="琼海" />
		<city label="三亚" />
		<city label="通什" />
		<city label="万宁" />
	</prov>
	<prov label="河北">
		<city label="石家庄" />
		<city label="保定" />
		<city label="北戴河" />
		<city label="沧州" />
		<city label="承德" />
		<city label="丰润" />
		<city label="邯郸" />
		<city label="衡水" />
		<city label="廊坊" />
		<city label="南戴河" />
		<city label="秦皇岛" />
		<city label="唐山" />
		<city label="新城" />
		<city label="邢台" />
		<city label="张家口" />
	</prov>
	<prov label="黑龙江">
		<city label="哈尔滨" />
		<city label="北安" />
		<city label="大庆" />
		<city label="大兴安岭" />
		<city label="鹤岗" />
		<city label="黑河" />
		<city label="佳木斯" />
		<city label="鸡西" />
		<city label="牡丹江" />
		<city label="齐齐哈尔" />
		<city label="七台河" />
		<city label="双鸭山" />
		<city label="绥化" />
		<city label="伊春" />
	</prov>
	<prov label="河南">
		<city label="郑州" />
		<city label="安阳" />
		<city label="鹤壁" />
		<city label="潢川" />
		<city label="焦作" />
		<city label="济源" />
		<city label="开封" />
		<city label="漯河" />
		<city label="洛阳" />
		<city label="南阳" />
		<city label="平顶山" />
		<city label="濮阳" />
		<city label="三门峡" />
		<city label="商丘" />
		<city label="新乡" />
		<city label="信阳" />
		<city label="许昌" />
		<city label="周口" />
		<city label="驻马店" />
	</prov>
	<prov label="香港">
		<city label="香港" />
		<city label="九龙" />
		<city label="新界" />
	</prov>
	<prov label="湖北">
		<city label="武汉" />
		<city label="恩施" />
		<city label="鄂州" />
		<city label="黄冈" />
		<city label="黄石" />
		<city label="荆门" />
		<city label="荆州" />
		<city label="潜江" />
		<city label="十堰" />
		<city label="随州" />
		<city label="武穴" />
		<city label="仙桃" />
		<city label="咸宁" />
		<city label="襄阳" />
		<city label="襄樊" />
		<city label="孝感" />
		<city label="宜昌" />
	</prov>
	<prov label="湖南">
		<city label="长沙" />
		<city label="常德" />
		<city label="郴州" />
		<city label="衡阳" />
		<city label="怀化" />
		<city label="吉首" />
		<city label="娄底" />
		<city label="邵阳" />
		<city label="湘潭" />
		<city label="益阳" />
		<city label="岳阳" />
		<city label="永州" />
		<city label="张家界" />
		<city label="株洲" />
	</prov>
	<prov label="江苏">
		<city label="南京" />
		<city label="常熟" />
		<city label="常州" />
		<city label="海门" />
		<city label="淮安" />
		<city label="江都" />
		<city label="江阴" />
		<city label="昆山" />
		<city label="连云港" />
		<city label="南通" />
		<city label="启东" />
		<city label="沭阳" />
		<city label="宿迁" />
		<city label="苏州" />
		<city label="太仓" />
		<city label="泰州" />
		<city label="同里" />
		<city label="无锡" />
		<city label="徐州" />
		<city label="盐城" />
		<city label="扬州" />
		<city label="宜兴" />
		<city label="仪征" />
		<city label="张家港" />
		<city label="镇江" />
		<city label="周庄" />
	</prov>
	<prov label="江西">
		<city label="南昌" />
		<city label="抚州" />
		<city label="赣州" />
		<city label="吉安" />
		<city label="景德镇" />
		<city label="井冈山" />
		<city label="九江" />
		<city label="庐山" />
		<city label="萍乡" />
		<city label="上饶" />
		<city label="新余" />
		<city label="宜春" />
		<city label="鹰潭" />
	</prov>
	<prov label="吉林">
		<city label="长春" />
		<city label="白城" />
		<city label="白山" />
		<city label="珲春" />
		<city label="辽源" />
		<city label="梅河" />
		<city label="吉林" />
		<city label="四平" />
		<city label="松原" />
		<city label="通化" />
		<city label="延吉" />
	</prov>
	<prov label="辽宁">
		<city label="沈阳" />
		<city label="鞍山" />
		<city label="本溪" />
		<city label="朝阳" />
		<city label="大连" />
		<city label="丹东" />
		<city label="抚顺" />
		<city label="阜新" />
		<city label="葫芦岛" />
		<city label="锦州" />
		<city label="辽阳" />
		<city label="盘锦" />
		<city label="铁岭" />
		<city label="营口" />
	</prov>
	<prov label="澳门">
		<city label="澳门" />
	</prov>
	<prov label="内蒙古">
		<city label="呼和浩特" />
		<city label="阿拉善盟" />
		<city label="包头" />
		<city label="赤峰" />
		<city label="东胜" />
		<city label="海拉尔" />
		<city label="集宁" />
		<city label="临河" />
		<city label="通辽" />
		<city label="乌海" />
		<city label="乌兰浩特" />
		<city label="锡林浩特" />
	</prov>
	<prov label="宁夏">
		<city label="银川" />
		<city label="固源" />
		<city label="石嘴山" />
		<city label="吴忠" />
	</prov>
	<prov label="青海">
		<city label="西宁" />
		<city label="德令哈" />
		<city label="格尔木" />
		<city label="共和" />
		<city label="海东" />
		<city label="海晏" />
		<city label="玛沁" />
		<city label="同仁" />
		<city label="玉树" />
	</prov>
	<prov label="山东">
		<city label="济南" />
		<city label="滨州" />
		<city label="兖州" />
		<city label="德州" />
		<city label="东营" />
		<city label="菏泽" />
		<city label="济宁" />
		<city label="莱芜" />
		<city label="聊城" />
		<city label="临沂" />
		<city label="蓬莱" />
		<city label="青岛" />
		<city label="曲阜" />
		<city label="日照" />
		<city label="泰安" />
		<city label="潍坊" />
		<city label="威海" />
		<city label="烟台" />
		<city label="枣庄" />
		<city label="淄博" />
	</prov>
	<prov label="上海">
		<city label="崇明" />
		<city label="黄浦" />
		<city label="卢湾" />
		<city label="徐汇" />
		<city label="长宁" />
		<city label="静安" />
		<city label="普陀" />
		<city label="闸北" />
		<city label="虹口" />
		<city label="杨浦" />
		<city label="闵行" />
		<city label="宝山" />
		<city label="嘉定" />
		<city label="浦东" />
		<city label="金山" />
		<city label="松江" />
		<city label="青浦" />
		<city label="南汇" />
		<city label="奉贤" />
	</prov>
	<prov label="山西">
		<city label="太原" />
		<city label="长治" />
		<city label="大同" />
		<city label="候马" />
		<city label="晋城" />
		<city label="离石" />
		<city label="临汾" />
		<city label="宁武" />
		<city label="朔州" />
		<city label="忻州" />
		<city label="阳泉" />
		<city label="榆次" />
		<city label="运城" />
	</prov>
	<prov label="陕西">
		<city label="西安" />
		<city label="安康" />
		<city label="宝鸡" />
		<city label="汉中" />
		<city label="渭南" />
		<city label="商州" />
		<city label="绥德" />
		<city label="铜川" />
		<city label="咸阳" />
		<city label="延安" />
		<city label="榆林" />
	</prov>
	<prov label="四川">
		<city label="成都" />
		<city label="巴中" />
		<city label="达川" />
		<city label="德阳" />
		<city label="都江堰" />
		<city label="峨眉山" />
		<city label="涪陵" />
		<city label="广安" />
		<city label="广元" />
		<city label="九寨沟" />
		<city label="康定" />
		<city label="乐山" />
		<city label="泸州" />
		<city label="马尔康" />
		<city label="绵阳" />
		<city label="眉山" />
		<city label="南充" />
		<city label="内江" />
		<city label="攀枝花" />
		<city label="遂宁" />
		<city label="汶川" />
		<city label="西昌" />
		<city label="雅安" />
		<city label="宜宾" />
		<city label="自贡" />
		<city label="资阳" />
	</prov>
	<prov label="台湾">
		<city label="台北" />
		<city label="基隆" />
		<city label="台南" />
		<city label="台中" />
		<city label="高雄" />
		<city label="屏东" />
		<city label="南投" />
		<city label="云林" />
		<city label="新竹" />
		<city label="彰化" />
		<city label="苗栗" />
		<city label="嘉义" />
		<city label="花莲" />
		<city label="桃园" />
		<city label="宜兰" />
		<city label="台东" />
		<city label="金门" />
		<city label="马祖" />
		<city label="澎湖" />
	</prov>
	<prov label="天津">
		<city label="天津" />
		<city label="和平" />
		<city label="东丽" />
		<city label="河东" />
		<city label="西青" />
		<city label="河西" />
		<city label="津南" />
		<city label="南开" />
		<city label="北辰" />
		<city label="河北" />
		<city label="武清" />
		<city label="红挢" />
		<city label="塘沽" />
		<city label="汉沽" />
		<city label="大港" />
		<city label="宁河" />
		<city label="静海" />
		<city label="宝坻" />
		<city label="蓟县" />
	</prov>
	<prov label="新疆">
		<city label="乌鲁木齐" />
		<city label="阿克苏" />
		<city label="阿勒泰" />
		<city label="阿图什" />
		<city label="博乐" />
		<city label="昌吉" />
		<city label="东山" />
		<city label="哈密" />
		<city label="和田" />
		<city label="喀什" />
		<city label="克拉玛依" />
		<city label="库车" />
		<city label="库尔勒" />
		<city label="奎屯" />
		<city label="石河子" />
		<city label="塔城" />
		<city label="吐鲁番" />
		<city label="伊宁" />
	</prov>
	<prov label="西藏">
		<city label="拉萨" />
		<city label="阿里" />
		<city label="昌都" />
		<city label="林芝" />
		<city label="那曲" />
		<city label="日喀则" />
		<city label="山南" />
	</prov>
	<prov label="云南">
		<city label="昆明" />
		<city label="大理" />
		<city label="保山" />
		<city label="楚雄" />
		<city label="大理" />
		<city label="东川" />
		<city label="个旧" />
		<city label="景洪" />
		<city label="开远" />
		<city label="临沧" />
		<city label="丽江" />
		<city label="六库" />
		<city label="潞西" />
		<city label="曲靖" />
		<city label="思茅" />
		<city label="文山" />
		<city label="西双版纳" />
		<city label="玉溪" />
		<city label="中甸" />
		<city label="昭通" />
	</prov>
	<prov label="浙江">
		<city label="杭州" />
		<city label="安吉" />
		<city label="慈溪" />
		<city label="定海" />
		<city label="奉化" />
		<city label="海盐" />
		<city label="黄岩" />
		<city label="湖州" />
		<city label="嘉兴" />
		<city label="金华" />
		<city label="临安" />
		<city label="临海" />
		<city label="丽水" />
		<city label="宁波" />
		<city label="瓯海" />
		<city label="平湖" />
		<city label="千岛湖" />
		<city label="衢州" />
		<city label="江山" />
		<city label="瑞安" />
		<city label="绍兴" />
		<city label="嵊州" />
		<city label="台州" />
		<city label="温岭" />
		<city label="温州" />
		<city label="余姚" />
		<city label="舟山" />
	</prov>
	<prov label="海外">
		<city label="欧洲" />
		<city label="北美" />
		<city label="南美" />
		<city label="亚洲" />
		<city label="非洲" />
		<city label="大洋洲" />
	</prov>
</data>
		
	}

}
